version: '3.7'

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: wea_grafana
    hostname: wea_grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "password"
      GF_DEFAULT_APP_MODE: "development"
      GF_INSTALL_PLUGINS: "https://github.com/meln5674/grafana-mongodb-community-plugin/releases/download/v0.2.0%2Brc4/meln5674-mongodb-community.zip;mongodb-community"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: mongodb-community
    ports:
     - 3000:3000
    networks: 
      - connector

networks:
  connector:

